services:
  front:
    build: front/
    ports:
      - 4200:80
  api:
    build: api/
    depends_on:
      - database
    ports:
      - "8081:80"
    volumes:
      - ./api/index.php:/var/www/html/index.php
      - ./api/properties.json:/var/www/html/properties.json
      - ./api/src:/var/www/html/src
      - ./api/crud:/var/www/html/crud

  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/0-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/1-data.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=epivia
      - POSTGRES_USER=unknown

volumes:
  pgadmin-data:
  db-data: